# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pskk_pb2 as pskk__pb2


class PSKKServiceStub(object):
  """PSKK IME Service
  Provides Japanese input method engine functionality over gRPC
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ProcessKey = channel.unary_unary(
        '/pskk.PSKKService/ProcessKey',
        request_serializer=pskk__pb2.KeyEvent.SerializeToString,
        response_deserializer=pskk__pb2.EngineOutput.FromString,
        )
    self.SetMode = channel.unary_unary(
        '/pskk.PSKKService/SetMode',
        request_serializer=pskk__pb2.SetModeRequest.SerializeToString,
        response_deserializer=pskk__pb2.EngineOutput.FromString,
        )
    self.GetMode = channel.unary_unary(
        '/pskk.PSKKService/GetMode',
        request_serializer=pskk__pb2.Empty.SerializeToString,
        response_deserializer=pskk__pb2.ModeResponse.FromString,
        )
    self.FocusOut = channel.unary_unary(
        '/pskk.PSKKService/FocusOut',
        request_serializer=pskk__pb2.Empty.SerializeToString,
        response_deserializer=pskk__pb2.EngineOutput.FromString,
        )
    self.Reset = channel.unary_unary(
        '/pskk.PSKKService/Reset',
        request_serializer=pskk__pb2.Empty.SerializeToString,
        response_deserializer=pskk__pb2.Empty.FromString,
        )
    self.GetConfig = channel.unary_unary(
        '/pskk.PSKKService/GetConfig',
        request_serializer=pskk__pb2.Empty.SerializeToString,
        response_deserializer=pskk__pb2.ConfigResponse.FromString,
        )
    self.ReloadConfig = channel.unary_unary(
        '/pskk.PSKKService/ReloadConfig',
        request_serializer=pskk__pb2.Empty.SerializeToString,
        response_deserializer=pskk__pb2.Empty.FromString,
        )
    self.GetDictionarySize = channel.unary_unary(
        '/pskk.PSKKService/GetDictionarySize',
        request_serializer=pskk__pb2.Empty.SerializeToString,
        response_deserializer=pskk__pb2.DictionarySizeResponse.FromString,
        )


class PSKKServiceServicer(object):
  """PSKK IME Service
  Provides Japanese input method engine functionality over gRPC
  """

  def ProcessKey(self, request, context):
    """Process a keyboard event
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetMode(self, request, context):
    """Set input mode (Alphanumeric or Hiragana)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMode(self, request, context):
    """Get current input mode
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FocusOut(self, request, context):
    """Handle focus out event
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Reset(self, request, context):
    """Reset engine state
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetConfig(self, request, context):
    """Get the current configuration
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReloadConfig(self, request, context):
    """Reload configuration from disk
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDictionarySize(self, request, context):
    """Get the dictionary size (number of yomi-to-kanji entries)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PSKKServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ProcessKey': grpc.unary_unary_rpc_method_handler(
          servicer.ProcessKey,
          request_deserializer=pskk__pb2.KeyEvent.FromString,
          response_serializer=pskk__pb2.EngineOutput.SerializeToString,
      ),
      'SetMode': grpc.unary_unary_rpc_method_handler(
          servicer.SetMode,
          request_deserializer=pskk__pb2.SetModeRequest.FromString,
          response_serializer=pskk__pb2.EngineOutput.SerializeToString,
      ),
      'GetMode': grpc.unary_unary_rpc_method_handler(
          servicer.GetMode,
          request_deserializer=pskk__pb2.Empty.FromString,
          response_serializer=pskk__pb2.ModeResponse.SerializeToString,
      ),
      'FocusOut': grpc.unary_unary_rpc_method_handler(
          servicer.FocusOut,
          request_deserializer=pskk__pb2.Empty.FromString,
          response_serializer=pskk__pb2.EngineOutput.SerializeToString,
      ),
      'Reset': grpc.unary_unary_rpc_method_handler(
          servicer.Reset,
          request_deserializer=pskk__pb2.Empty.FromString,
          response_serializer=pskk__pb2.Empty.SerializeToString,
      ),
      'GetConfig': grpc.unary_unary_rpc_method_handler(
          servicer.GetConfig,
          request_deserializer=pskk__pb2.Empty.FromString,
          response_serializer=pskk__pb2.ConfigResponse.SerializeToString,
      ),
      'ReloadConfig': grpc.unary_unary_rpc_method_handler(
          servicer.ReloadConfig,
          request_deserializer=pskk__pb2.Empty.FromString,
          response_serializer=pskk__pb2.Empty.SerializeToString,
      ),
      'GetDictionarySize': grpc.unary_unary_rpc_method_handler(
          servicer.GetDictionarySize,
          request_deserializer=pskk__pb2.Empty.FromString,
          response_serializer=pskk__pb2.DictionarySizeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pskk.PSKKService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
